### ISSUE TITLE
Does not work with newer versions of Homebridge

### ISSUE THREAD

**Issue by PappyChappy1** [joepool/homebridge-cmdswitch2-no-logs#5]
Causing fatal error: Homebridge v2.0.0-alpha.2 (HAP v1.0.0) (homebridge-cmdswitch2) is running on port 48904.

/opt/homebrew/lib/node_modules/homebridge-cmdswitch2-no-logs/index.js:145
  accessory.updateReachability(true);
            ^
TypeError: accessory.updateReachability is not a function
    at cmdSwitchPlatform.getInitState (/opt/homebrew/lib/node_modules/homebridge-cmdswitch2-no-logs/index.js:145:13)
    at cmdSwitchPlatform.addAccessory (/opt/homebrew/lib/node_modules/homebridge-cmdswitch2-no-logs/index.js:99:8)
    at cmdSwitchPlatform.didFinishLaunching (/opt/homebrew/lib/node_modules/homebridge-cmdswitch2-no-logs/index.js:36:37)
    at HomebridgeAPI.emit (node:events:519:28)
    at HomebridgeAPI.signalFinished (/opt/homebrew/lib/node_modules/homebridge/src/api.ts:271:10)
    at ChildBridgeFork.startBridge (/opt/homebrew/lib/node_modules/homebridge/src/childBridgeFork.ts:194:14)

**Comment by PappyChappy1** [comment]
Looks like the homebridge team is issuing a warning about the new version breaking plugins, any chance you can update @joepool ?  I know this hasn't needed an update in a few years but I love this plugin and don't want to lose functionality

**Comment by joepool** [comment]
I'll give it a look over at some point next week and see what I can do!

**Comment by joepool** [comment]
I have just published a beta version that should fix this issue, please test and report back @PappyChappy1 

Also, having looked over the code for the first time in about 4 years I realised how awful it is, when I'm really bored this plugin could really do with being rewritten!

**Comment by PappyChappy1** [comment]
It works with the latest versions of the Homebridge Alpha and Beta - thanks @joepool ! Have to keep reverting back to the older version of Homebridge though because so many other plugins break on 2.0

**Comment by joepool** [comment]
Glad all is working, have just published final version.

**Comment by YellowNest** [comment]
The plugin is not working with Homebridge 2.0.0-betal.11
